services:
  postgres:
    image: postgres:16-alpine3.20
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - catpay
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  catpay:
    driver: bridge
