services:
  postgres:
    image: postgres:16-alpine3.20
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - catpay
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data

networks:
  catpay:
    driver: bridge
